<?php
namespace common\controllers;

use common\common\ErrDesc;
use common\models\Book;
use yii\web\Controller;

class ReadBaseController extends Controller {
    public $enableCsrfValidation = false;
    public $layout = 'read';
    public $requestData;

    public function beforeAction($action)
    {
        $userAgent = $_SERVER['HTTP_USER_AGENT'];     //限制pc或移动端浏览
        $pos = strstr($userAgent,'mobile');
        if(!empty($pos)){
            die('请使用pc端浏览');
        }
        $this->requestData = array_merge(\Yii::$app->request->get(), \Yii::$app->request->post());
        if(array_key_exists('r', $this->requestData))
            unset($this->requestData['r']);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function rtJson($code=ErrDesc::OK, $data=[])
    {
        $rtMsg = [
            'code' => $code,
            'msg' => ErrDesc::$DESC[$code],
            'data' => $data
        ];
        return $this->asJson($rtMsg);
    }

    public function getClientParam($param, $default='')
    {
        if(array_key_exists($param, $this->requestData )) {
            return trim($this->requestData[$param]);
        }
        return $default;
    }
    public function actionGetClick(){
        $model = new Book();
        $model->click = 1;
        $model->update();
        return $this->rtJson(ErrDesc::OK);
    }
    public function actionGetSave(){
        $model = new Book();
        $model->save = $model->save+1;
        $model->update();
        return $this->rtJson(ErrDesc::OK);
    }
}